// AUTO-GENERATED by glm-generate-tests.ts using GLM-4.7
// Date: 2026-03-16T03:39:42.512Z
// Models: gpt-oss-120b
import { test, expect } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

const BASE    = process.env.FPT_API_URL!;
const KEY     = process.env.FPT_API_KEY!;
const FROM    = process.env.FPT_FROM!;
const HEADERS = { 'Content-Type': 'application/json', 'Authorization': `Bearer ${KEY}` };

function chatUrl(model: string) { return `${BASE}/v1/chat/completions?from=${FROM}&model=${model}`; }
function chatBody(model: string, content: string, extra: object = {}) {
  return { model, messages: [{ role: 'user', content }], streaming: false, temperature: 1, max_tokens: 512, top_p: 1, top_k: 40, presence_penalty: 0, frequency_penalty: 0, ...extra };
}
async function assertChat(res: any, model: string) {
  expect(res.status(), `${model} should return 200`).toBe(200);
  const body = await res.json();
  expect(body).toHaveProperty('choices');
  const content = body.choices[0].message?.content ?? '';
  expect(content.length).toBeGreaterThan(0);
  console.log(`✅ ${model}: "${content.substring(0, 80)}..."`);
  return body;
}

const MSG_SHORT  = 'Hi, what is your name and version?';
const MSG_FAMILY = "Hi! My name is Ethan, I'm 7. My family: father (engineer, 40), mother (teacher, 37), baby sister Lisa (2).";

test.describe('Chat Completions — Generated by GLM-4.7', () => {
  test('TC_API_100 — gpt-oss-120b', async ({ request }) => {
    const res = await request.post(chatUrl('gpt-oss-120b'), {
      headers: HEADERS,
      data: chatBody('gpt-oss-120b', MSG_FAMILY),
    });
    await assertChat(res, 'gpt-oss-120b');
  });
});