/**
 * fpt-api-health.check.js
 * AUTO-GENERATED by utils/generate-checkly-checks.js
 * Date: 2026-04-09T05:39:18.724Z
 * VN: 18 active | JP: 18 active
 *
 * To regenerate: node utils/generate-checkly-checks.js
 * To deploy:     npx checkly deploy --force
 */

const { ApiCheck, AssertionBuilder, Frequency } = require('checkly/constructs');

const BASE_VN = process.env.FPT_API_URL    || 'https://mkp-api.fptcloud.com';
const BASE_JP = process.env.FPT_JP_API_URL || 'https://mkp-api.fptcloud.jp';
const FROM    = process.env.FPT_FROM       || 'thuanlt9';

const HEADERS_VN = [
  { key: 'Content-Type',  value: 'application/json' },
  { key: 'Authorization', value: 'Bearer {{FPT_API_KEY}}' },
];
const HEADERS_JP = [
  { key: 'Content-Type',  value: 'application/json' },
  { key: 'Authorization', value: 'Bearer {{FPT_JP_API_KEY}}' },
];

// ═══════════════════════════════════════════════════
//  VN SITE — mkp-api.fptcloud.com
// ═══════════════════════════════════════════════════

new ApiCheck('vn-glm-4-7', {
  name:      '🤖 [VN] GLM-4.7',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=GLM-4.7`,
    headers: HEADERS_VN,
    body:    `{"model":"GLM-4.7","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-gpt-oss-120b', {
  name:      '🤖 [VN] gpt-oss-120b',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=gpt-oss-120b`,
    headers: HEADERS_VN,
    body:    `{"model":"gpt-oss-120b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-gpt-oss-20b', {
  name:      '🤖 [VN] gpt-oss-20b',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=gpt-oss-20b`,
    headers: HEADERS_VN,
    body:    `{"model":"gpt-oss-20b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-qwen3-32b', {
  name:      '🤖 [VN] Qwen3-32B',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=Qwen3-32B`,
    headers: HEADERS_VN,
    body:    `{"model":"Qwen3-32B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-gemma-3-27b-it', {
  name:      '🤖 [VN] gemma-3-27b-it',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=gemma-3-27b-it`,
    headers: HEADERS_VN,
    body:    `{"model":"gemma-3-27b-it","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-saola3-1-medium', {
  name:      '🤖 [VN] SaoLa3.1-medium',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=SaoLa3.1-medium`,
    headers: HEADERS_VN,
    body:    `{"model":"SaoLa3.1-medium","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-saola-llama3-1-planner', {
  name:      '🤖 [VN] SaoLa-Llama3.1-planner',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=SaoLa-Llama3.1-planner`,
    headers: HEADERS_VN,
    body:    `{"model":"SaoLa-Llama3.1-planner","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-llama-3-3-70b-instruct', {
  name:      '🤖 [VN] Llama-3.3-70B-Instruct',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=Llama-3.3-70B-Instruct`,
    headers: HEADERS_VN,
    body:    `{"model":"Llama-3.3-70B-Instruct","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-kimi-k2-5', {
  name:      '🤖 [VN] Kimi-K2.5',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=Kimi-K2.5`,
    headers: HEADERS_VN,
    body:    `{"model":"Kimi-K2.5","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-saola4-medium', {
  name:      '🤖 [VN] SaoLa4-medium',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=SaoLa4-medium`,
    headers: HEADERS_VN,
    body:    `{"model":"SaoLa4-medium","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-saola4-small', {
  name:      '🤖 [VN] SaoLa4-small',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=SaoLa4-small`,
    headers: HEADERS_VN,
    body:    `{"model":"SaoLa4-small","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-nemotron-3-super-120b-a12b', {
  name:      '🤖 [VN] Nemotron-3-Super-120B-A12B',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=Nemotron-3-Super-120B-A12B`,
    headers: HEADERS_VN,
    body:    `{"model":"Nemotron-3-Super-120B-A12B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-qwen2-5-vl-7b-instruct', {
  name:      '👁️ [VN] Qwen2.5-VL-7B-Instruct',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=Qwen2.5-VL-7B-Instruct`,
    headers: HEADERS_VN,
    body:    `{"model":"Qwen2.5-VL-7B-Instruct","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-fpt-ai-kie-v1-7', {
  name:      '👁️ [VN] FPT.AI-KIE-v1.7',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/chat/completions?from=${FROM}&model=FPT.AI-KIE-v1.7`,
    headers: HEADERS_VN,
    body:    `{"model":"FPT.AI-KIE-v1.7","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('vn-multilingual-e5-large', {
  name:      '📐 [VN] multilingual-e5-large',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'embedding'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/embeddings?from=${FROM}&model=multilingual-e5-large`,
    headers: HEADERS_VN,
    body:    `{"model":"multilingual-e5-large","input":"Hello world test."}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.data').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('vn-vietnamese-embedding', {
  name:      '📐 [VN] Vietnamese_Embedding',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'embedding'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/embeddings?from=${FROM}&model=Vietnamese_Embedding`,
    headers: HEADERS_VN,
    body:    `{"model":"Vietnamese_Embedding","input":"Hello world test."}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.data').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('vn-bge-reranker-v2-m3', {
  name:      '🔍 [VN] bge-reranker-v2-m3',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'rerank'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/rerank?from=${FROM}&model=bge-reranker-v2-m3`,
    headers: HEADERS_VN,
    body:    `{"model":"bge-reranker-v2-m3","query":"What is AI?","documents":["AI is artificial intelligence.","The sky is blue."]}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.results').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('vn-fpt-ai-vits', {
  name:      '🔊 [VN] FPT.AI-VITs',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vn', 'tts'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_VN}/v1/audio/speech?from=${FROM}&model=FPT.AI-VITs`,
    headers: HEADERS_VN,
    body:    `{"model":"FPT.AI-VITs","input":"Hello.","voice":"alloy"}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

// ═══════════════════════════════════════════════════
//  JP SITE — mkp-api.fptcloud.jp
// ═══════════════════════════════════════════════════

new ApiCheck('jp-kimi-k2-5', {
  name:      '🤖 [JP] Kimi-K2.5',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=Kimi-K2.5`,
    headers: HEADERS_JP,
    body:    `{"model":"Kimi-K2.5","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-saola4-medium', {
  name:      '🤖 [JP] SaoLa4-medium',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=SaoLa4-medium`,
    headers: HEADERS_JP,
    body:    `{"model":"SaoLa4-medium","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-saola4-small', {
  name:      '🤖 [JP] SaoLa4-small',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=SaoLa4-small`,
    headers: HEADERS_JP,
    body:    `{"model":"SaoLa4-small","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-glm-4-7', {
  name:      '🤖 [JP] GLM-4.7',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=GLM-4.7`,
    headers: HEADERS_JP,
    body:    `{"model":"GLM-4.7","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-gpt-oss-120b', {
  name:      '🤖 [JP] gpt-oss-120b',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=gpt-oss-120b`,
    headers: HEADERS_JP,
    body:    `{"model":"gpt-oss-120b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-gpt-oss-20b', {
  name:      '🤖 [JP] gpt-oss-20b',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=gpt-oss-20b`,
    headers: HEADERS_JP,
    body:    `{"model":"gpt-oss-20b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-qwen3-32b', {
  name:      '🤖 [JP] Qwen3-32B',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=Qwen3-32B`,
    headers: HEADERS_JP,
    body:    `{"model":"Qwen3-32B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-llama-3-3-70b-instruct', {
  name:      '🤖 [JP] Llama-3.3-70B-Instruct',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=Llama-3.3-70B-Instruct`,
    headers: HEADERS_JP,
    body:    `{"model":"Llama-3.3-70B-Instruct","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-nemotron-3-super-120b-a12b', {
  name:      '🤖 [JP] Nemotron-3-Super-120B-A12B',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=Nemotron-3-Super-120B-A12B`,
    headers: HEADERS_JP,
    body:    `{"model":"Nemotron-3-Super-120B-A12B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-qwen2-5-vl-7b-instruct', {
  name:      '👁️ [JP] Qwen2.5-VL-7B-Instruct',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=Qwen2.5-VL-7B-Instruct`,
    headers: HEADERS_JP,
    body:    `{"model":"Qwen2.5-VL-7B-Instruct","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-gemma-3-27b-it', {
  name:      '👁️ [JP] gemma-3-27b-it',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=gemma-3-27b-it`,
    headers: HEADERS_JP,
    body:    `{"model":"gemma-3-27b-it","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-fpt-ai-kie-v1-7', {
  name:      '👁️ [JP] FPT.AI-KIE-v1.7',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=FPT.AI-KIE-v1.7`,
    headers: HEADERS_JP,
    body:    `{"model":"FPT.AI-KIE-v1.7","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-gemma-4-31b-it', {
  name:      '👁️ [JP] gemma-4-31B-it',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=gemma-4-31B-it`,
    headers: HEADERS_JP,
    body:    `{"model":"gemma-4-31B-it","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-gemma-4-26b-a4b-it', {
  name:      '👁️ [JP] gemma-4-26B-A4B-it',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=gemma-4-26B-A4B-it`,
    headers: HEADERS_JP,
    body:    `{"model":"gemma-4-26B-A4B-it","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-fci-document-parsing-v1-0', {
  name:      '👁️ [JP] FCI-Document-Parsing-V1.0',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/chat/completions?from=${FROM}&model=FCI-Document-Parsing-V1.0`,
    headers: HEADERS_JP,
    body:    `{"model":"FCI-Document-Parsing-V1.0","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('jp-multilingual-e5-large', {
  name:      '📐 [JP] multilingual-e5-large',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'embedding'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/embeddings?from=${FROM}&model=multilingual-e5-large`,
    headers: HEADERS_JP,
    body:    `{"model":"multilingual-e5-large","input":"Hello world test."}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.data').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('jp-bge-reranker-v2-m3', {
  name:      '🔍 [JP] bge-reranker-v2-m3',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'rerank'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/rerank?from=${FROM}&model=bge-reranker-v2-m3`,
    headers: HEADERS_JP,
    body:    `{"model":"bge-reranker-v2-m3","query":"What is AI?","documents":["AI is artificial intelligence.","The sky is blue."]}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.results').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('jp-boltz-2', {
  name:      '🧬 [JP] Boltz-2',
  activated: true,
  frequency: Frequency.EVERY_1H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'jp', 'protein'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE_JP}/v1/predict?from=${FROM}&model=Boltz-2`,
    headers: HEADERS_JP,
    body:    `{"model":"Boltz-2","polymers":[{"id":"A","molecule_type":"protein","sequence":"MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR"}],"ligands":[{"id":"ASP","smiles":"CC(=O)OC1=CC=CC=C1C(=O)O","predict_affinity":true}],"recycling_steps":3,"sampling_steps":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});
