/**
 * fpt-api-health.check.js
 * AUTO-GENERATED by utils/generate-checkly-checks.js
 * Date: 2026-03-25T18:00:13.646Z
 * Models: 24 active (6 skipped)
 *
 * To regenerate: node utils/generate-checkly-checks.js
 * To deploy:     npx checkly deploy --force
 */

const { ApiCheck, AssertionBuilder, Frequency } = require('checkly/constructs');

const BASE    = process.env.FPT_API_URL || 'https://mkp-api.fptcloud.com';
const FROM    = process.env.FPT_FROM    || 'thuanlt9';
const KEY     = process.env.FPT_API_KEY || '';
const HEADERS = [
  { key: 'Content-Type',  value: 'application/json' },
  { key: 'Authorization', value: `Bearer ${KEY}` },
];

new ApiCheck('deepseek-v3-2-speciale', {
  name:      '🤖 DeepSeek-V3.2-Speciale',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=DeepSeek-V3.2-Speciale`,
    headers: HEADERS,
    body:    `{"model":"DeepSeek-V3.2-Speciale","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('glm-4-7', {
  name:      '🤖 GLM-4.7',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=GLM-4.7`,
    headers: HEADERS,
    body:    `{"model":"GLM-4.7","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('gpt-oss-120b', {
  name:      '🤖 gpt-oss-120b',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=gpt-oss-120b`,
    headers: HEADERS,
    body:    `{"model":"gpt-oss-120b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('gpt-oss-20b', {
  name:      '🤖 gpt-oss-20b',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=gpt-oss-20b`,
    headers: HEADERS,
    body:    `{"model":"gpt-oss-20b","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('qwen2-5-coder-32b-instruct', {
  name:      '🤖 Qwen2.5-Coder-32B-Instruct',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Qwen2.5-Coder-32B-Instruct`,
    headers: HEADERS,
    body:    `{"model":"Qwen2.5-Coder-32B-Instruct","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('qwen3-32b', {
  name:      '🤖 Qwen3-32B',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Qwen3-32B`,
    headers: HEADERS,
    body:    `{"model":"Qwen3-32B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('gemma-3-27b-it', {
  name:      '🤖 gemma-3-27b-it',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=gemma-3-27b-it`,
    headers: HEADERS,
    body:    `{"model":"gemma-3-27b-it","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('saola3-1-medium', {
  name:      '🤖 SaoLa3.1-medium',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=SaoLa3.1-medium`,
    headers: HEADERS,
    body:    `{"model":"SaoLa3.1-medium","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('saola-llama3-1-planner', {
  name:      '🤖 SaoLa-Llama3.1-planner',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=SaoLa-Llama3.1-planner`,
    headers: HEADERS,
    body:    `{"model":"SaoLa-Llama3.1-planner","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('llama-3-3-70b-instruct', {
  name:      '🤖 Llama-3.3-70B-Instruct',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Llama-3.3-70B-Instruct`,
    headers: HEADERS,
    body:    `{"model":"Llama-3.3-70B-Instruct","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('llama-3-3-swallow-70b-instruct-v0-4', {
  name:      '🤖 Llama-3.3-Swallow-70B-Instruct-v0.4',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Llama-3.3-Swallow-70B-Instruct-v0.4`,
    headers: HEADERS,
    body:    `{"model":"Llama-3.3-Swallow-70B-Instruct-v0.4","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('kimi-k2-5', {
  name:      '🤖 Kimi-K2.5',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Kimi-K2.5`,
    headers: HEADERS,
    body:    `{"model":"Kimi-K2.5","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('saola4-medium', {
  name:      '🤖 SaoLa4-medium',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=SaoLa4-medium`,
    headers: HEADERS,
    body:    `{"model":"SaoLa4-medium","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('saola4-small', {
  name:      '🤖 SaoLa4-small',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=SaoLa4-small`,
    headers: HEADERS,
    body:    `{"model":"SaoLa4-small","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('nemotron-3-super-120b-a12b', {
  name:      '🤖 Nemotron-3-Super-120B-A12B',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'chat'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Nemotron-3-Super-120B-A12B`,
    headers: HEADERS,
    body:    `{"model":"Nemotron-3-Super-120B-A12B","messages":[{"role":"user","content":"Hi, reply with one word: OK"}],"streaming":false,"max_tokens":10}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});

new ApiCheck('qwen3-vl-8b-instruct', {
  name:      '👁️ Qwen3-VL-8B-Instruct',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Qwen3-VL-8B-Instruct`,
    headers: HEADERS,
    body:    `{"model":"Qwen3-VL-8B-Instruct","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(60000),
    ],
  },
});

new ApiCheck('qwen2-5-vl-7b-instruct', {
  name:      '👁️ Qwen2.5-VL-7B-Instruct',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Qwen2.5-VL-7B-Instruct`,
    headers: HEADERS,
    body:    `{"model":"Qwen2.5-VL-7B-Instruct","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(60000),
    ],
  },
});

new ApiCheck('deepseek-ocr', {
  name:      '👁️ DeepSeek-OCR',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=DeepSeek-OCR`,
    headers: HEADERS,
    body:    `{"model":"DeepSeek-OCR","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(60000),
    ],
  },
});

new ApiCheck('alpamayo-r1-10b', {
  name:      '👁️ Alpamayo-R1-10B',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=Alpamayo-R1-10B`,
    headers: HEADERS,
    body:    `{"model":"Alpamayo-R1-10B","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(60000),
    ],
  },
});

new ApiCheck('fpt-ai-kie-v1-7', {
  name:      '👁️ FPT.AI-KIE-v1.7',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'vision'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/chat/completions?from=${FROM}&model=FPT.AI-KIE-v1.7`,
    headers: HEADERS,
    body:    `{"model":"FPT.AI-KIE-v1.7","messages":[{"role":"user","content":[{"type":"text","text":"What is in this image?"},{"type":"image_url","image_url":{"url":"https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"}}]}],"streaming":false,"max_tokens":50}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.choices').isNotNull(),
      AssertionBuilder.responseTime().lessThan(60000),
    ],
  },
});

new ApiCheck('multilingual-e5-large', {
  name:      '📐 multilingual-e5-large',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'embedding'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/embeddings?from=${FROM}&model=multilingual-e5-large`,
    headers: HEADERS,
    body:    `{"model":"multilingual-e5-large","input":"Hello world test."}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.data').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('vietnamese-embedding', {
  name:      '📐 Vietnamese_Embedding',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'embedding'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/embeddings?from=${FROM}&model=Vietnamese_Embedding`,
    headers: HEADERS,
    body:    `{"model":"Vietnamese_Embedding","input":"Hello world test."}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.data').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('bge-reranker-v2-m3', {
  name:      '🔍 bge-reranker-v2-m3',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'rerank'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/rerank?from=${FROM}&model=bge-reranker-v2-m3`,
    headers: HEADERS,
    body:    `{"model":"bge-reranker-v2-m3","query":"What is AI?","documents":["AI is artificial intelligence.","The sky is blue."]}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.jsonBody('$.results').isNotNull(),
      AssertionBuilder.responseTime().lessThan(15000),
    ],
  },
});

new ApiCheck('fpt-ai-vits', {
  name:      '🔊 FPT.AI-VITs',
  activated: false,
  frequency: Frequency.EVERY_6H,
  locations: ['ap-southeast-1'],
  tags:      ['fpt', 'tts'],
  degradedResponseTime: 5000,
  maxResponseTime:      30000,
  request: {
    method:  'POST',
    url:     `${BASE}/v1/audio/speech?from=${FROM}&model=FPT.AI-VITs`,
    headers: HEADERS,
    body:    `{"model":"FPT.AI-VITs","input":"Hello.","voice":"alloy"}`,
    assertions: [
      AssertionBuilder.statusCode().equals(200),
      AssertionBuilder.responseTime().lessThan(30000),
    ],
  },
});
