// AUTO-GENERATED by glm-direct.ts using GLM-4.7
// Date: 2026-03-16T16:37:25.870Z
// Task: Viết TC_NEMOTRON_007 kiểm tra streaming response từ Nemotron-3-Super-120B-A12B qua FPT API STG. Gọi 

import { test, expect } from '@playwright/test';
import { config } from '../../utils/config';

const MODEL_API_ID = 'Nemotron-3-Super-120B-A12B';

test.use({ storageState: 'playwright/.auth/stg-user.json' });

test.describe('Nemotron — Regression STG', () => {
  test('TC_NEMOTRON_007 — Verify streaming response via API', async ({ request }) => {
    const response = await request.post(`${config.fptApiUrl}/v1/chat/completions`, {
      headers: {
        'Authorization': `Bearer ${config.fptApiKey}`,
        'Content-Type': 'application/json',
      },
      data: {
        model: MODEL_API_ID,
        messages: [
          {
            role: 'user',
            content: 'Write a short greeting.',
          },
        ],
        stream: true,
        max_tokens: 50,
      },
    });

    expect(response.ok()).toBeTruthy();

    const responseBody = await response.text();
    const lines = responseBody.split('\n').filter((line) => line.trim() !== '');

    let hasTextChunk = false;

    for (const line of lines) {
      // Check for SSE termination signal
      if (line.includes('[DONE]')) {
        continue;
      }

      // Verify SSE format
      expect(line).toMatch(/^data: /);

      const jsonStr = line.replace(/^data: /, '');
      let chunk;

      try {
        chunk = JSON.parse(jsonStr);
      } catch (e) {
        throw new Error(`Failed to parse SSE chunk: ${jsonStr}`);
      }

      // Verify chunk structure
      expect(chunk).toHaveProperty('choices');
      expect(Array.isArray(chunk.choices)).toBeTruthy();

      if (chunk.choices.length > 0) {
        const choice = chunk.choices[0];
        expect(choice).toHaveProperty('delta');
        expect(choice).toHaveProperty('index');

        // Nemotron is a reasoning model — delta may have 'reasoning' before 'content'
        // At least one of 'content' or 'reasoning' must be present in each delta
        const hasField = 'content' in choice.delta || 'reasoning' in choice.delta || Object.keys(choice.delta).length === 0;
        expect(hasField).toBeTruthy();

        // Count 'reasoning' chunks too — Nemotron may stream reasoning only
        const content = choice.delta.content ?? '';
        const reasoning = choice.delta.reasoning ?? '';
        if (content.length > 0 || reasoning.length > 0) {
          hasTextChunk = true;
        }
      }
    }

    // Assert that we actually received some streamed text (content or reasoning)
    expect(hasTextChunk).toBeTruthy();
  });
});