// Generated by OpenClaw Agent — NCPP-6392
import { test, expect } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

const BASE = process.env.FPT_API_URL!;
const KEY = process.env.FPT_API_KEY!;
const FROM = process.env.FPT_FROM!;
const HEADERS = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${KEY}`,
};

test.describe('NCPP-6392 — [Test]Contact us', () => {
  test('TC_NCPP_6392_001 — Gửi yêu cầu hỗ trợ thành công (Happy Path) [API]', async ({ request }) => {
    const payload = {
      name: 'Nguyễn Văn A',
      email: 'nguyenvana@example.com',
      companySize: '51-200',
      phone: '0123456789',
      subject: "I'd like to request a new feature/model",
      message: 'Tôi muốn có mô hình dự báo thời tiết',
    };

    const response = await request.post(`${BASE}/api/contact?from=${FROM}`, {
      headers: HEADERS,
      data: payload,
    });

    expect(response.status()).toBe(200);
    const body = await response.json();

    // Basic sanity checks – adapt according to actual API contract
    expect(body).toHaveProperty('success', true);
    expect(body).toHaveProperty('data');
    expect(body.data).toMatchObject({
      name: payload.name,
      email: payload.email,
      companySize: payload.companySize,
      phone: payload.phone,
      subject: payload.subject,
      message: payload.message,
    });
  });

  test('TC_NCPP_6392_005 — Kiểm tra danh sách và lựa chọn Company size [API]', async ({ request }) => {
    const selectedSize = '201-500';
    const payload = {
      name: 'Test User',
      email: 'test.user@example.com',
      companySize: selectedSize,
      phone: '0987654321',
      subject: 'Testing company size selection',
      message: 'Just a test message.',
    };

    const response = await request.post(`${BASE}/api/contact?from=${FROM}`, {
      headers: HEADERS,
      data: payload,
    });

    expect(response.status()).toBe(200);
    const body = await response.json();

    // Verify that the selected company size is reflected in the response payload
    expect(body).toHaveProperty('success', true);
    expect(body).toHaveProperty('data');
    expect(body.data).toMatchObject({
      companySize: selectedSize,
    });
  });
});