// Generated by OpenClaw Agent — NCPP-6392
import { test, expect } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

const BASE_URL = process.env.FPT_API_URL!;
const API_KEY = process.env.FPT_API_KEY!;
const FROM = process.env.FPT_FROM!;
const HEADERS = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${API_KEY}`,
};

test.describe('NCPP-6392 — [Test]Contact us', () => {
  test('TC_NCPP_6392_001 — Gửi yêu cầu hỗ trợ thành công (Happy Path) [API]', async ({ request }) => {
    const payload = {
      from: FROM,
      name: 'Nguyễn Văn A',
      email: 'nguyenvana@example.com',
      companySize: '11-50',
      phone: '0909 123 456',
      featureRequest: 'I would like to request a new feature.',
      message: 'This is a test message for the contact us form.'
    };

    const response = await request.post(`${BASE_URL}/contact-us`, {
      headers: HEADERS,
      data: payload,
    });

    expect(response.status()).toBe(200);
    const body = await response.json();
    // Assuming the API returns a field `success` and a `message`
    expect(body).toHaveProperty('success', true);
    expect(body).toHaveProperty('message', 'Your message has been successfully sent. Our team will get back to you as soon as possible.');
    // Verify that the payload was echoed back (optional, depends on API design)
    expect(body).toHaveProperty('data');
    expect(body.data).toMatchObject({
      name: payload.name,
      email: payload.email,
      companySize: payload.companySize,
      phone: payload.phone,
      featureRequest: payload.featureRequest,
      message: payload.message,
    });
  });

  test('TC_NCPP_6392_005 — Kiểm tra danh sách và giá trị gửi của dropdown Company size [API]', async ({ request }) => {
    const companySizes = ['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+'];
    for (const size of companySizes) {
      const payload = {
        from: FROM,
        name: 'Test User',
        email: 'testuser@example.com',
        companySize: size,
        // optional fields can be omitted or set to empty strings
        phone: '',
        featureRequest: '',
        message: ''
      };

      const response = await request.post(`${BASE_URL}/contact-us`, {
        headers: HEADERS,
        data: payload,
      });

      expect(response.status(), `Failed for companySize ${size}`).toBe(200);
      const body = await response.json();
      expect(body).toHaveProperty('success', true);
      expect(body).toHaveProperty('data');
      expect(body.data).toMatchObject({ companySize: size });
    }
  });
});