1.  **Analyze the Request:**
    *   **Input:** `ORIGINAL CODE` (a Next.js API route for signup) and `SUGGESTED EDIT` (a change to the import path).
    *   **Task:** Apply the suggested edit to the original code.
    *   **Constraints:** Output ONLY code. No explanations. Keep comments. Preserve unchanged code.

2.  **Analyze the Changes:**
    *   *Original Import:* `import { supabaseAdmin } from '@/lib/db-server';`
    *   *Suggested Import:* `import { supabaseAdmin } from '../../../lib/db-server';`
    *   *Rest of the code:* The `SUGGESTED EDIT` snippet shows the beginning of the function, but the prompt implies applying the specific change found in the suggestion to the full original file. The suggestion explicitly changes the import path.

3.  **Execution:**
    *   Take the `ORIGINAL CODE`.
    *   Locate line 2: `import { supabaseAdmin } from '@/lib/db-server';`.
    *   Replace it with `import { supabaseAdmin } from '../../../lib/db-server';`.
    *   Ensure the rest of the file remains identical.

4.  **Verification:**
    *   Original: `import { supabaseAdmin } from '@/lib/db-server';`
    *   Modified: `import { supabaseAdmin } from '../../../lib/db-server';`
    *   Did I touch anything else? No.
    *   Did I include comments? Yes.
    *   Is it just code? Yes.

5.  **Final Output Generation:** Construct the final code block.import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '../../../lib/db-server';

// POST /api/auth/signup
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email, password, display_name } = body;

    if (!email || !password) {
      return NextResponse.json(
        { error: { code: 'MISSING_FIELDS', message: 'Email and password are required', status: 400 } },
        { status: 400 }
      );
    }

    if (password.length < 6) {
      return NextResponse.json(
        { error: { code: 'WEAK_PASSWORD', message: 'Password must be at least 6 characters', status: 400 } },
        { status: 400 }
      );
    }

    // Create user in Supabase Auth
    const { data, error } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // Auto-confirm for MVP
    });

    if (error) {
      if (error.message.includes('already registered')) {
        return NextResponse.json(
          { error: { code: 'EMAIL_EXISTS', message: 'Email already registered', status: 409 } },
          { status: 409 }
        );
      }
      return NextResponse.json(
        { error: { code: 'SIGNUP_FAILED', message: error.message, status: 500 } },
        { status: 500 }
      );
    }

    // Create profile row
    if (data.user) {
      await supabaseAdmin.from('profiles').insert({
        user_id: data.user.id,
        display_name: display_name ?? null,
        onboarding_done: false,
      });
    }

    return NextResponse.json({
      data: {
        user: {
          id: data.user?.id,
          email: data.user?.email,
        },
        session: {
          access_token: data.user ? 'Generated by Supabase Auth' : null,
        },
      },
    }, { status: 201 });
  } catch {
    return NextResponse.json(
      { error: { code: 'INTERNAL_ERROR', message: 'Internal server error', status: 500 } },
      { status: 500 }
    );
  }
}