/**
 * glm-generate-tests.ts
 * Uses GLM-4.7 (FPT Cloud) to generate Playwright test cases for new API models.
 *
 * Usage:
 *   npx ts-node utils/glm-generate-tests.ts "ModelA" "ModelB"
 *   npx ts-node utils/glm-generate-tests.ts          # uses demo models
 */
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';
import { fetch, ProxyAgent } from 'undici';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const API_BASE = process.env.FPT_API_URL!;
const API_KEY  = process.env.FPT_API_KEY!;
const API_FROM = process.env.FPT_FROM!;

const PROXY = process.env.https_proxy || process.env.HTTPS_PROXY || process.env.http_proxy || process.env.HTTP_PROXY;
const dispatcher = PROXY ? new ProxyAgent(PROXY) : undefined;
if (PROXY) console.log(`🔌 Using proxy: ${PROXY}`);

async function callGLM(prompt: string, maxTokens = 2048): Promise<{ content: string; usage: any }> {
  const res = await fetch(
    `${API_BASE}/v1/chat/completions?from=${API_FROM}&model=GLM-4.7`,
    {
      method:     'POST',
      headers:    { 'Content-Type': 'application/json', 'Authorization': `Bearer ${API_KEY}` },
      body:       JSON.stringify({
        model:       'GLM-4.7',
        messages:    [{ role: 'user', content: prompt }],
        streaming:   false,
        temperature: 0.2,
        max_tokens:  maxTokens,
      }),
      dispatcher,
    } as any
  );
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  const body: any = await res.json();
  const msg = body.choices[0].message;
  const content = msg.content ?? msg.reasoning_content ?? '';
  return { content, usage: body.usage };
}

const PATTERN = `
// ── Helpers (already defined in spec file) ──────────────────────────────────
function chatUrl(model: string) {
  return \`\${BASE}/v1/chat/completions?from=\${FROM}&model=\${model}\`;
}
function chatBody(model: string, content: string) {
  return { model, messages: [{ role: 'user', content }], streaming: false,
    temperature: 1, max_tokens: 512, top_p: 1, top_k: 40,
    presence_penalty: 0, frequency_penalty: 0 };
}
async function assertChat(res: any, model: string) { /* validates 200 + choices */ }

const MSG_SHORT  = 'Hi, what is your name and version?';
const MSG_FAMILY = "Hi! My name is Ethan, I'm 7. My family: father (engineer, 40), mother (teacher, 37), baby sister Lisa (2).";

// ── Example test ──────────────────────────────────────────────────────────
test('TC_API_003 — GLM-4.7', async ({ request }) => {
  const res = await request.post(chatUrl('GLM-4.7'), {
    headers: HEADERS,
    data: chatBody('GLM-4.7', MSG_FAMILY),
  });
  await assertChat(res, 'GLM-4.7');
});

// ── Example vision test ───────────────────────────────────────────────────
test('TC_API_020 — DeepSeek-OCR (with image URL)', async ({ request }) => {
  const res = await request.post(chatUrl('DeepSeek-OCR'), {
    headers: HEADERS,
    data: {
      model: 'DeepSeek-OCR',
      messages: [{ role: 'user', content: [
        { type: 'text', text: 'What is this a picture of?' },
        { type: 'image_url', image_url: { url: 'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg' } },
      ]}],
      streaming: false, temperature: 1, max_tokens: 512,
    },
  });
  await assertChat(res, 'DeepSeek-OCR');
});
`.trim();

const ALREADY_TESTED_VN = [
  'DeepSeek-V3.2-Speciale', 'GLM-4.5', 'GLM-4.7', 'gpt-oss-120b', 'gpt-oss-20b',
  'Qwen2.5-Coder-32B-Instruct', 'Qwen3-32B', 'Qwen3-Coder-480B-A35B-Instruct',
  'gemma-3-27b-it', 'SaoLa3.1-medium', 'SaoLa-Llama3.1-planner',
  'Llama-3.3-70B-Instruct', 'Llama-3.3-Swallow-70B-Instruct-v0.4',
  'Kimi-K2.5', 'SaoLa4-medium', 'SaoLa4-small',
  'Qwen3-VL-8B-Instruct', 'Qwen2.5-VL-7B-Instruct',
  'DeepSeek-OCR', 'FPT.AI-Table-Parsing-v1.1', 'FPT.AI-KIE-v1.7',
];

async function generateTests(models: string[], startIndex = 100): Promise<string> {
  const prompt = `You are a senior QA engineer writing Playwright TypeScript API tests for FPT AI Marketplace.

## Existing test pattern (DO follow this exactly):
\`\`\`typescript
${PATTERN}
\`\`\`

## Models already covered: ${ALREADY_TESTED_VN.join(', ')}

## Task:
Generate Playwright test cases for these NEW models: **${models.join(', ')}**

Rules:
1. Use TC_API_${startIndex} numbering (increment for each test)
2. Text-only models → use MSG_FAMILY or MSG_SHORT
3. Vision/multimodal models → use image_url pattern (use the Det.jpg URL from example)
4. Wrap all tests in a test.describe block named 'Chat Completions — Generated by GLM-4.7'
5. Output ONLY valid TypeScript code, no markdown fences, no explanations
6. Keep the same coding style: async/await, assertChat helper, HEADERS constant`;

  console.log(`\n🤖 GLM-4.7 đang generate test cases cho: ${models.join(', ')}\n`);

  const { content, usage } = await callGLM(prompt, 2048);
  console.log(`📊 Tokens — prompt: ${usage?.prompt_tokens}, completion: ${usage?.completion_tokens}, total: ${usage?.total_tokens}\n`);
  return content;
}

async function main() {
  const models = process.argv.slice(2);
  const targetModels = models.length > 0
    ? models
    : ['Qwen3-VL-72B-Instruct', 'GLM-Z1-Air', 'SaoLa4-large'];  // demo defaults

  const code = await generateTests(targetModels);

  console.log('─'.repeat(60));
  console.log('Generated test cases:');
  console.log('─'.repeat(60));
  console.log(code);

  // Optionally save to file
  const outFile = path.resolve(__dirname, '../tests/api/api-generated.spec.ts');
  const header = `// AUTO-GENERATED by glm-generate-tests.ts using GLM-4.7\n// Date: ${new Date().toISOString()}\n// Models: ${targetModels.join(', ')}\nimport { test, expect } from '@playwright/test';\nimport dotenv from 'dotenv';\ndotenv.config();\n\nconst BASE    = process.env.FPT_API_URL!;\nconst KEY     = process.env.FPT_API_KEY!;\nconst FROM    = process.env.FPT_FROM!;\nconst HEADERS = { 'Content-Type': 'application/json', 'Authorization': \`Bearer \${KEY}\` };\n\nfunction chatUrl(model: string) { return \`\${BASE}/v1/chat/completions?from=\${FROM}&model=\${model}\`; }\nfunction chatBody(model: string, content: string, extra: object = {}) {\n  return { model, messages: [{ role: 'user', content }], streaming: false, temperature: 1, max_tokens: 512, top_p: 1, top_k: 40, presence_penalty: 0, frequency_penalty: 0, ...extra };\n}\nasync function assertChat(res: any, model: string) {\n  expect(res.status(), \`\${model} should return 200\`).toBe(200);\n  const body = await res.json();\n  expect(body).toHaveProperty('choices');\n  const content = body.choices[0].message?.content ?? '';\n  expect(content.length).toBeGreaterThan(0);\n  console.log(\`✅ \${model}: "\${content.substring(0, 80)}..."\`);\n  return body;\n}\n\nconst MSG_SHORT  = 'Hi, what is your name and version?';\nconst MSG_FAMILY = "Hi! My name is Ethan, I'm 7. My family: father (engineer, 40), mother (teacher, 37), baby sister Lisa (2).";\n\n`;
  fs.writeFileSync(outFile, header + code, 'utf-8');
  console.log(`\n✅ Saved to: ${outFile}`);
}

main().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
